name: smb-admin
version: 0.6
summary: SMB Solution Admin Service
description: Admin service for the SMB Solution.
grade: stable
confinement: strict

apps:
    smb-admin:
      command: bin/run-service-admin
      daemon: simple
      plugs:
        - network
        - network-bind
        - system-observe
        - snapd-control
    smb-user:
      command: bin/run-service
      daemon: simple
      plugs:
        - network
        - network-bind
        - system-observe
        - snapd-control
parts:
    service:
        plugin: go
        source: git://github.com/ubuntu-core/smb-admin
        go-importpath: github.com/ubuntu-core/smb-admin
    assets:
        source: static
        plugin: dump
        organize:
            "build-admin": static/build-admin
            "build-enduser": static/build-enduser
    scripts:
        source: bin
        plugin: dump
        organize:
            "run-service": bin/run-service
            "run-service-admin": bin/run-service-admin
    languages:
        source: lang
        plugin: dump
        organize:
            "*": lang/
